version: "3.7"

services:
  sample:
    container_name: sample
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
    ports:
      - 0.0.0.0:3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
